version: '3.8'

services:
  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: '${username}'
      MINIO_ROOT_PASSWORD: '${password}'
    env_file:
      - minio.env
    volumes:
      - ~/minio/data:/data
    command: server /data --console-address ":9001"

  minio-restore:
    image: quay.io/minio/minio
    container_name: minio-restore
    ports:
      - "9002:9000"
      - "9003:9001"
    environment:
      MINIO_ROOT_USER: '${username}'
      MINIO_ROOT_PASSWORD: '${password}'
    env_file:
      - minio.env
    volumes:
      - ~/minio/data:/data
    command: server /data --console-address ":9001"
    